run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Проверка обработки ошибок
    - gosimple      # Упрощение кода
    - govet         # Проверка корректности кода
    - ineffassign   # Неиспользуемые присваивания
    - staticcheck   # Статический анализ
    - unused        # Неиспользуемый код
    - gofmt         # Форматирование
    - goimports     # Импорты
    - misspell      # Орфография
    - revive        # Стиль кода
    - gosec         # Безопасность

linters-settings:
  errcheck:
    check-blank: true
  
  govet:
    check-shadowing: true
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: context-as-argument
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

