run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Проверка обработки ошибок
    - gosimple      # Упрощение кода
    - govet         # Проверка корректности кода
    - ineffassign   # Неиспользуемые присваивания
    - staticcheck   # Статический анализ
    - unused        # Неиспользуемый код
    - gofmt         # Форматирование
    - goimports     # Импорты
    - misspell      # Орфография
    - revive        # Стиль кода
    - gosec         # Безопасность

linters-settings:
  errcheck:
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: false
  
  goimports:
    local-prefixes: github.com/reviewer-service
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: if-return
        severity: warning
  
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: cmd/server/main.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck

